### ISSUE TITLE
As a developer I need to Create Data Models for the application entities

### ISSUE THREAD

**Issue by zacck** [LittleKidogo/spender#14]
So here what I am aiming for is to get all the models and tests for the application entities built in the application layer. Currently, I am  using Ecto Schemas as models however I am aware there is a better was of doing this using an Intent-Based Approach, however, this is out of reach for me currently but will be revisiting it

**Comment by zacck-zz** [comment]
@WanjikuMac  @br4inii  this was mostly finished by you!!! Thank you so much for the time, the help dedication

**Comment by r-coh** [comment]
You welcome!! @zacck
