### ISSUE TITLE
Create Model for PaymentMethod

### ISSUE THREAD

**Issue by zacck** [LittleKidogo/spender#20]
A PaymentMethod is one of the methods that an application user has when doing expenses e.g Cash, Card, Cheque, Crypto .... This feature is currently used for logging and is intended as research to bank account integration this item currently has the following fields 

- name: the name of this method
- money_log_id: id of money_log
- balance: amount unspent in this 

A model will need to 
- [ ] Create a Payment Method when a name and a money_log_id are provided 
- [ ] Update the balance of MoneyLog  when a valid id sent with the new balance
- [ ] Update the name of the PaymentMethod

**Comment by WanjikuMac** [comment]
I can work on this

**Comment by WanjikuMac** [comment]
Is the model supposed to be `update the name of the MoneyLog` or `Update the money log id` ?

**Comment by zacck-zz** [comment]
@WanjikuMac hey I think I updated the description to explain this better, it meant to say that the model should be able to update the name of the `PaymentMethod`
