### ISSUE TITLE
Create Model for LogCategory

### ISSUE THREAD

**Issue by zacck** [LittleKidogo/spender#25]
A LogCategory contains a record of all the categories that a user intends to spend on in a money log this is usually created as the budget is getting refined, it will contain the following field 
- id: a system generated id 
- name: name of this category 
- money_log_id: id of the MoneyLog for this category 

a model will be needed to 
- [ ] create a LogCategory 
- [ ] update a LogCategory's details 
- [ ] delete a LogCategory

**Comment by WanjikuMac** [comment]
I am working on this issue
