### ISSUE TITLE
Create Model for ExpenseLog

### ISSUE THREAD

**Issue by zacck** [LittleKidogo/spender#26]
An ExpenseLog is generated everytime a user spends in a MoneyLog, it contains the following details 
- name: name of this expense 
- log_category_id: id of the LogCategory this expense belongs to
- desc: a description of this expense 
- amount: amount spent in this expense 
- payment_method_id: id of PaymentMethod used for this expense 
- money_log_id: id of MoneyLog this expense belongs to
- date: date of this expense 

A model will be needed to 
- [ ] Create an expense if name and amount spent provided 
- [ ] Update expense details if id is provided

**Comment by zacck-zz** [comment]
## Notes
Needs to be associated to a Payment Method #113
