### ISSUE TITLE
Create Model for SavingLog

### ISSUE THREAD

**Issue by zacck** [LittleKidogo/spender#27]
A SavingLog is used to record an instance where a PurchaseItem is ticked off and the price in the ExpensLog  lower than that of the PurchaseItem or alternatively when the total spent in a section is less than the total of PurchaseItems in the section, it will contain the following fields 

- name: name of the SavingLog 
- amount: amount saved 
- log_category_id: name of the LogCategory this saving is attributed to 
- money_log _id: id of the MoneyLog this SavingsLog belongs to

a model will be needed to 
- [ ] Create a savings log 
- [ ] Update a savings log

**Comment by WanjikuMac** [comment]
I can work on this issue

**Comment by zacck-zz** [comment]
@WanjikuMac  I think @br4inii  got to this one first so let's let him have it
